In [1]:
#import load_model class for loading h5 file
from tensorflow.keras.models import load_model
#import image class to process the images
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.inception_v3 import preprocess_input
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/Drive')


Mounted at /Drive


In [6]:
#load saved model file
model=load_model('/Drive/MyDrive/ibm/model/Updated-Xception-diabetic-retinopathy.h5')

In [11]:
#load one random image from local system
img=image.load_img('/Drive/MyDrive/ibm/static/test.png',target_size=(299,299))

In [12]:
#convert image to array format
x=image.img_to_array(img)

In [13]:
import matplotlib.pyplot as plt

In [14]:
x.shape

(299, 299, 3)

In [15]:
import numpy as np
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 299, 299, 3)

In [16]:
model.predict(img_data)

1/1 [==============================] - 2s 2s/step


array([[9.9999964e-01, 9.0790226e-15, 3.1074288e-07, 6.0327455e-16,
        1.5835224e-11]], dtype=float32)

In [17]:
output=np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 414ms/step


In [18]:
output==0,output==1,output==2,output==3,output==4

(array([ True]),
 array([False]),
 array([False]),
 array([False]),
 array([False]))

In [19]:
index=['No Diabetic Retinopathy', 'Mild DR', 'Moderate DR', 'Severe DR', 'Proliferative DR']
result = str(index[output[0]])
result

'No Diabetic Retinopathy'